# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bc6b7fe31f50cbd9fad60d5a021401c3b1d82f7b399ea5f3b079a6cdece60d12f54f64a9a62baa6e89d8a015d2eff58812bc8e374b5e5efc024fd901653dd137

test:
  secret_key_base: bc4182c6f0356abe3888fe8fdae632b774785859e0f2d7df33e383a264831ef29fec3d0cda1ace80eaced121a2e0bee4f668077bd8349489699fa17e5fcd685a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
